name: Add Reviewers to PR
on:
  pull_request:
    types: [ready_for_review]
jobs:
  auto-attach-reviewers:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: Add Reviewers
        uses: madrapps/add-reviewers@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: DudkoMatt,castlesofplacebo,Igor-bite
          re-request-when-approved: true
          re-request-when-changes-requested: true
