name: Pull Request on New Feature
on:
  create:
    branches:
      - "feature/**"
jobs:
  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        shell: bash
        run: GH_REF="${{ github.ref }}"; echo "BRANCH_NAME=$(echo ${GH_REF##*/})" >> $GITHUB_ENV
      - name: Create Pull Request
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "feature/"
          PULL_REQUEST_BRANCH: "develop"
          PULL_REQUEST_BODY: "This is the automated pull request for reviewing new feature"
          PULL_REQUEST_TITLE: "Feature/${{ env.BRANCH_NAME }}"
          PULL_REQUEST_DRAFT: true
      - name: Assign Pull Request to Project
        uses: technote-space/create-project-card-action@v1
        with:
          PROJECT: "Translate On The Go"
          COLUMN: ${{ github.actor }}
